dotenv: .env
wallets:
  private_key: ${PRIVATE_KEY}

dependecies:
  - smartcontractkit/chainlink-brownie-contracts@0.3.0

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.0"